version: "3"

services:
  app:
    user: node
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspace
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: node
    command: /bin/sh -c "while sleep 1000; do :; done"
